import { GitLabConfig, AndroidFile } from "../types";
import { STARTER_PROJECT } from "../data/defaultTemplates";
import { auditAndSanitizeForGitHub } from "./githubClient";

export interface GitLabSafetyAudit {
  isSafe: boolean;
  warnings: string[];
  sanitizedFiles: AndroidFile[];
  leakedSecretsDetected: boolean;
}

/**
 * Standard Android GitLab CI/CD Configuration File (.gitlab-ci.yml)
 */
export const GITLAB_CI_CONTENT = `# GitLab CI/CD Pipeline for Android APK Builder
# Pre-configured with Android SDK 34, JDK 17 & Gradle
image: ghcr.io/cirruslabs/android-sdk:34

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

stages:
  - build
  - release

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/caches/
    - .gradle/wrapper/

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew || true

assembleDebug:
  stage: build
  script:
    - if [ -f "./gradlew" ]; then ./gradlew assembleDebug --stacktrace; else gradle assembleDebug --stacktrace; fi
    - mkdir -p build-apks
    - find app/build/outputs/apk/ -name "*.apk" -exec cp {} build-apks/ \\; || true
    - ls -la build-apks/
  artifacts:
    name: "android-apk-$CI_COMMIT_REF_NAME"
    paths:
      - build-apks/*.apk
      - app/build/outputs/apk/debug/*.apk
    expire_in: 30 days
    when: always

assembleRelease:
  stage: build
  script:
    - if [ -f "./gradlew" ]; then ./gradlew assembleRelease --stacktrace || true; else gradle assembleRelease --stacktrace || true; fi
    - mkdir -p build-apks
    - find app/build/outputs/apk/ -name "*.apk" -exec cp {} build-apks/ \\; || true
  artifacts:
    name: "android-release-apk-$CI_COMMIT_REF_NAME"
    paths:
      - build-apks/*.apk
      - app/build/outputs/apk/release/*.apk
    expire_in: 30 days
    when: on_success
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
      allow_failure: true

gitlab-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating GitLab Release for $CI_COMMIT_TAG"
  release:
    tag_name: '$CI_COMMIT_TAG'
    name: 'Android APK Release $CI_COMMIT_TAG'
    description: 'Automated Android APK compiled by GitLab CI/CD Pipeline. Download APK from artifacts.'
`;

/**
 * Sanitizes GitLab input path, supporting full URLs or owner/project names
 */
export function sanitizeGitLabInputs(
  projectIdOrPath?: string,
  instanceUrl?: string
): { cleanProject: string; cleanInstance: string; encodedProject: string } {
  let rawProject = (projectIdOrPath || "").trim();
  let rawInstance = (instanceUrl || "https://gitlab.com").trim().replace(/\/+$/, "");

  if (rawProject.startsWith("http://") || rawProject.startsWith("https://")) {
    try {
      const url = new URL(rawProject);
      rawInstance = `${url.protocol}//${url.host}`;
      rawProject = url.pathname.replace(/^\/+/, "").replace(/\.git$/, "").replace(/\/+$/, "");
    } catch (e) {
      // fallback
    }
  }

  // Remove leading @ or slashes
  rawProject = rawProject.replace(/^@/, "").replace(/^\/+|\/+$/g, "");
  if (!rawProject) {
    rawProject = "rehmanmobilez786/Android-apk-builder-studio";
  }

  // GitLab REST API uses URL-encoded project path (slash is replaced with %2F) or numeric ID
  const encodedProject = encodeURIComponent(rawProject);

  return {
    cleanProject: rawProject,
    cleanInstance: rawInstance || "https://gitlab.com",
    encodedProject,
  };
}

/**
 * Ensures project files contain both Android files and .gitlab-ci.yml
 */
export function ensureGitLabProjectFiles(currentFiles: AndroidFile[]): AndroidFile[] {
  const fileMap = new Map<string, AndroidFile>();

  STARTER_PROJECT.files.forEach((f) => fileMap.set(f.path, f));
  currentFiles.forEach((f) => {
    if (f.path && f.content !== undefined) {
      fileMap.set(f.path, f);
    }
  });

  // Ensure .gitlab-ci.yml is included
  if (!fileMap.has(".gitlab-ci.yml")) {
    fileMap.set(".gitlab-ci.yml", {
      path: ".gitlab-ci.yml",
      content: GITLAB_CI_CONTENT,
      isAutoGenerated: true,
    });
  }

  return Array.from(fileMap.values());
}

// Cooldown to avoid GitLab abuse
let lastGitLabSyncTimestamp = 0;
const MIN_GITLAB_SYNC_COOLDOWN_MS = 3000;

/**
 * Direct GitLab multi-file atomic commit via GitLab REST API v4
 */
export async function directGitLabSync(
  config: GitLabConfig,
  files: AndroidFile[]
): Promise<{
  success: boolean;
  message: string;
  url?: string;
  pipelinesUrl?: string;
  warnings?: string[];
}> {
  const { token, projectIdOrPath, instanceUrl, branch = "main" } = config;

  if (!token || !token.trim()) {
    return {
      success: false,
      message: "⚠️ برائے مہربانی GitLab Personal Access Token (PAT) درج کریں (Scopes: 'api' یا 'write_repository')۔",
    };
  }

  const now = Date.now();
  if (now - lastGitLabSyncTimestamp < MIN_GITLAB_SYNC_COOLDOWN_MS) {
    return {
      success: false,
      message: "⏳ برائے مہربانی چند لمحے انتظار کریں۔ فوری پش کرنے سے GitLab API Rate Limit کا خطرہ ہوتا ہے۔",
    };
  }
  lastGitLabSyncTimestamp = now;

  const { cleanProject, cleanInstance, encodedProject } = sanitizeGitLabInputs(projectIdOrPath, instanceUrl);
  const cleanBranch = (branch || "main").trim();
  const cleanToken = token.trim();

  // Audit secrets and ensure .gitlab-ci.yml is in the bundle
  const completeFiles = ensureGitLabProjectFiles(files);
  const audit = auditAndSanitizeForGitHub(completeFiles);
  const filesToPush = audit.sanitizedFiles;

  const headers = {
    "PRIVATE-TOKEN": cleanToken,
    "Content-Type": "application/json",
  };

  const projectUrl = `${cleanInstance}/${cleanProject}`;
  const pipelinesUrl = `${cleanInstance}/${cleanProject}/-/pipelines`;

  try {
    // 1. Verify GitLab Project Access
    const projectRes = await fetch(`${cleanInstance}/api/v4/projects/${encodedProject}`, {
      headers,
    });

    if (projectRes.status === 401) {
      return {
        success: false,
        message: "❌ GitLab Token غیر معتبر (Unauthorized / 401) ہے۔ براہ کرم درست Personal Access Token داخل کریں جس میں 'api' یا 'write_repository' کی پرمیشن ہو۔",
      };
    }

    if (projectRes.status === 404) {
      return {
        success: false,
        message: `❌ پروجیکٹ '${cleanProject}' GitLab پر نہیں ملا (404)۔ براہ کرم تصدیق کریں کہ پروجیکٹ پاتھ اور Instance URL (${cleanInstance}) درست ہیں۔`,
      };
    }

    if (!projectRes.ok) {
      const errText = await projectRes.text().catch(() => projectRes.statusText);
      return {
        success: false,
        message: `❌ GitLab سے رابطہ میں خرابی (${projectRes.status}): ${errText}`,
      };
    }

    // 2. Fetch existing repository tree to know which files to 'create' vs 'update'
    let existingPaths = new Set<string>();
    try {
      const treeRes = await fetch(
        `${cleanInstance}/api/v4/projects/${encodedProject}/repository/tree?ref=${cleanBranch}&recursive=true&per_page=100`,
        { headers }
      );
      if (treeRes.ok) {
        const treeItems = await treeRes.json();
        if (Array.isArray(treeItems)) {
          treeItems.forEach((item: any) => {
            if (item.type === "blob") {
              existingPaths.add(item.path);
            }
          });
        }
      }
    } catch (e) {
      console.warn("Could not fetch GitLab tree list, will attempt smart actions", e);
    }

    // 3. Prepare Atomic Multi-Action Commit for GitLab
    const actions = filesToPush.map((file) => {
      const exists = existingPaths.has(file.path);
      return {
        action: exists ? "update" : "create",
        file_path: file.path,
        content: file.content,
      };
    });

    const commitPayload = {
      branch: cleanBranch,
      commit_message: `✨ Deploy Android APK Project & GitLab CI/CD Pipeline (${filesToPush.length} files) [GitLab Cloud CI]`,
      actions,
    };

    const commitRes = await fetch(
      `${cleanInstance}/api/v4/projects/${encodedProject}/repository/commits`,
      {
        method: "POST",
        headers,
        body: JSON.stringify(commitPayload),
      }
    );

    if (commitRes.ok) {
      return {
        success: true,
        message: `✅ GitLab پر تمام ${filesToPush.length} فائلیں (بشمول .gitlab-ci.yml اور مکمل Android سورس) ایک ہی اٹامک کمٹ میں پش ہو گئیں! GitLab CI/CD پائپ لائن خودکار طور پر فعال ہو گئی ہے۔`,
        url: projectUrl,
        pipelinesUrl,
        warnings: audit.warnings,
      };
    }

    // If commit failed (e.g. branch doesn't exist yet or some action conflicted), inspect error
    const commitErr = await commitRes.json().catch(() => ({ message: commitRes.statusText }));
    const errorMsg = commitErr.message || JSON.stringify(commitErr);

    // If branch doesn't exist, create it from default branch or first commit
    if (errorMsg.includes("does not exist") || errorMsg.includes("Branch")) {
      // Try committing with start_branch or create branch
      const initBranchRes = await fetch(
        `${cleanInstance}/api/v4/projects/${encodedProject}/repository/branches?branch=${cleanBranch}&ref=main`,
        { method: "POST", headers }
      );
      if (initBranchRes.ok) {
        // Retry commit once
        const retryRes = await fetch(
          `${cleanInstance}/api/v4/projects/${encodedProject}/repository/commits`,
          { method: "POST", headers, body: JSON.stringify(commitPayload) }
        );
        if (retryRes.ok) {
          return {
            success: true,
            message: `✅ برانچ بنا کر تمام ${filesToPush.length} فائلیں کامیابی سے GitLab پر پش ہو گئیں!`,
            url: projectUrl,
            pipelinesUrl,
          };
        }
      }
    }

    return {
      success: false,
      message: `❌ GitLab کمٹ ایرر: ${errorMsg}`,
    };
  } catch (err: any) {
    const errMsg = err?.message || String(err);
    return {
      success: false,
      message: `❌ GitLab سے رابطہ منقطع: ${errMsg}. براہ کرم تصدیق کریں کہ انٹرنیٹ اور GitLab Token درست ہیں۔`,
    };
  }
}

/**
 * Creates a Release on GitLab via GitLab REST API v4
 */
export async function directGitLabRelease(
  config: GitLabConfig,
  tagName: string = "v1.0.0",
  notes: string = "Automated Android APK release from GitLab CI/CD"
): Promise<{ success: boolean; message: string; releaseUrl?: string }> {
  const { token, projectIdOrPath, instanceUrl, branch = "main" } = config;

  if (!token || !token.trim()) {
    return {
      success: false,
      message: "⚠️ GitLab پر ریلیز بنانے کے لیے Personal Access Token داخل کریں۔",
    };
  }

  const { cleanProject, cleanInstance, encodedProject } = sanitizeGitLabInputs(projectIdOrPath, instanceUrl);
  const cleanBranch = (branch || "main").trim();
  const cleanToken = token.trim();

  try {
    const res = await fetch(`${cleanInstance}/api/v4/projects/${encodedProject}/releases`, {
      method: "POST",
      headers: {
        "PRIVATE-TOKEN": cleanToken,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        tag_name: tagName,
        ref: cleanBranch,
        name: `Android APK Release ${tagName}`,
        description: `${notes}\n\n📱 Compiled via GitLab CI/CD (.gitlab-ci.yml)\n🚀 Ready for testing and production deployment.`,
      }),
    });

    if (res.ok) {
      const data = await res.json();
      return {
        success: true,
        message: `✅ GitLab پر ریلیز ${tagName} کامیابی سے شایع ہو گئی!`,
        releaseUrl: data._links?.self || `${cleanInstance}/${cleanProject}/-/releases`,
      };
    }

    const err = await res.json().catch(() => ({ message: res.statusText }));
    return {
      success: false,
      message: `❌ GitLab ریلیز ایرر: ${err.message || res.statusText}`,
    };
  } catch (err: any) {
    return {
      success: false,
      message: `❌ GitLab ریلیز فیل: ${err?.message || err}`,
    };
  }
}
